name: dart_anchor_link_flutter_dialog_transport
description: Transport used by dart_anchor_link to show a dialog in Flutter with a QR code and a button to launch the local Anchor Wallet
version: 0.0.1
homepage: https://github.com/TheRealPaco/dart-anchor-link-flutter-dialog-transport

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2+1
  qr_flutter: ^3.2.0
  url_launcher: ^5.5.0
  url_launcher_web: ^0.1.2+1
  dart_esr:
    git: 
      url: https://github.com/EOS-Nation/dart-esr
      ref: feature/complete-port-of-esr-js
  dart_anchor_link:
    path: /home/paco/Documents/dev/eosn/dart-anchor-link

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: